# Generated by Django 2.2.12 on 2022-02-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
